---
userShell: /bin/bash
rootInstallation: true
autologinGroup: autologin
sudoersGroup: wheel

defaultGroups:
  - name: users
    must_exist: true
    system: false
  - name: wheel
    must_exist: false
    system: true
  - name: audio
    must_exist: false
    system: true
  - name: video
    must_exist: false
    system: true
  - name: network
    must_exist: false
    system: true
  - name: storage
    must_exist: false
    system: true
  - name: optical
    must_exist: false
    system: true

doAutologin: false
setRootPassword: true
doReusePassword: false

passwordRequirements:
    nonempty: true
    minLength: 6
